---
title: "lab3"
author: "Owen Kim"
date: "2024-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidyr)
library(readr)
```
##### Get the data into a format where the five columns for Death[1-5] are replaced by two columns: Time, and Death. Time should be a number between 1 and 5 (look into the function parse_number); Death is a categorical variables with values "yes", "no" and "". Call the resulting data set deaths.

```{r}
av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)

deaths <- av %>%
  pivot_longer(
    cols = starts_with("Death"),
    names_to = "Time",
    values_to = "Death"
  ) %>%
  mutate(
    Time = parse_number(Time),
    Death = factor(Death, levels = c("YES", "NO", ""))
  )

show(deaths$Time)
show(deaths$Death)
```

##### Count the number of deaths (rows with "yes" in the Death column) for each Avenger

```{r}
average_deaths <- deaths %>%
  filter(Death == "YES") %>%
  summarize(avg_deaths = n() / n_distinct(av))

show(average_deaths)
```